export const slidesData = {
  totalSlides: 19,
  slides: [
    { id: 0, name: "Hero", component: "SlideHero" },
    { id: 1, name: "Tagline", component: "SlideTagline" },
    { id: 2, name: "Tech Power", component: "SlideTechPower" },
    { id: 3, name: "Question", component: "SlideQuestion" },
    { id: 4, name: "Digital Chaos", component: "SlideDigitalChaos" },
    { id: 5, name: "Problem", component: "SlideProblem" },
    { id: 6, name: "Story", component: "SlideStory" },
    { id: 7, name: "Human Design", component: "SlideHumanDesign" },
    { id: 8, name: "One Platform", component: "SlideOnePlatform" },
    { id: 9, name: "Recognize", component: "SlideRecognize" },
    { id: 10, name: "Order System", component: "SlideOrderSystem" },
    { id: 11, name: "HR Module", component: "SlideHR" },
    { id: 12, name: "GPS Module", component: "SlideGPS" },
    { id: 13, name: "Task Module", component: "SlideTask" },
    { id: 14, name: "Analytics Module", component: "SlideAnalytics" },
    { id: 15, name: "4 Modules", component: "SlideFourModules" },
    { id: 16, name: "More Than Platform", component: "SlideMoreThan" },
    { id: 17, name: "XCard Bonus", component: "SlideXCard" },
    { id: 18, name: "Future", component: "SlideFuture" },
  ],
};
